### ISSUE TITLE
Connection to www.l214.com problem

### ISSUE THREAD

**Issue by tiflopin** [w3c/markup-validator#33]
Checking https://www.l214.com I get the message "500 Can't connect to www.l214.com:443".
https://validator.w3.org/check?uri=https://www.l214.com/

But the website is up for everybody else and the certificate seems to be ok : 
https://www.sslshopper.com/ssl-checker.html#hostname=www.l214.com

**Comment by tiflopin** [comment]
Somebody would found at least a workaround ?

**Comment by tiflopin** [comment]
Nobody ? ;-(

**Comment by ylafon** [comment]
Looks like it was a transient issue as the validator can access it.
