### ISSUE TITLE
This validator represents itself as the current validator at validator.w3.org

### ISSUE THREAD

**Issue by Alex-Jordan** [w3c/markup-validator#35]
This validator represents itself as the current validator at validator.w3.org, but it appears that the [nu validator](https://github.com/validator/validator) is in use there. This caused some confusion tonight. I suggest taking down the link to validator.w3.org and updating the README.md.

**Comment by xfq** [comment]
IIRC this validator redirects to The Nu Html Checker if the document is an HTML5 document.

**Comment by Alex-Jordan** [comment]
Ah OK. But what I mean is that the [github landing page](https://github.com/w3c/markup-validator) has a link to https://validator.w3.org/ at the top of the page, and the README.md doesn't mention the redirect. I'm having trouble remembering exactly what happened that night, but something (Google? a link at https://validator.w3.org/ ?) led us here. And there was no easy way to see that this was not the validator that was creating the output we had been shown.
