### ISSUE TITLE
Where's the FeedValidator repo?

### ISSUE THREAD

**Issue by jhabdas** [w3c/markup-validator#41]
https://sourceforge.net/projects/feedvalidator/

linked from the feed validation page on W3C site but not here on the GitHubs. There a particular reason for that? I'm opening this here as RSS uses XML, which is essentially SGML markup.

**Comment by sideshowbarker** [comment]
https://github.com/rubys/feedvalidator

**Comment by jhabdas** [comment]
Okay, so not [the one](http://sourceforge.net/projects/feedvalidator) linked from https://validator.w3.org/feed/ then. Got it. Thanks!
