### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by matsaman** [w3c/markup-validator#42]
It doesn't appear to be the validator at validator.w3.org, even though that is claimed.
Is this the future version that will be available from there?

**Comment by sideshowbarker** [comment]
It is the source for the validator at https://validator.w3.org/

**Comment by matsaman** [comment]
@sideshowbarker no it isn't.

If it were I would file issues about how it is validating against WHATWG's HTML spec instead of the W3C's own HTML spec. But it isn't so I won't be doing that ... unless it will be eventually?
