### ISSUE TITLE
ports

### ISSUE THREAD

**Issue by EndeavourAccuracy** [w3c/markup-validator#44]
Quoting from (emphasis mine): https://validator.w3.org/services#ip-address
"Traffic from W3C Validator services will be coming from 128.30.52.**0/24** subnet and you may firewall or block that in your web server configuration."

It's also visiting from 128.30.52.**134**.

**Comment by NagyD** [comment]
As I understand it, "/24" means that the first 24 bits (first 3 bytes) are fixed, the rest (the last byte) can vary.
Therefore, the 128.30.52.0/24 subnet means the range 128.30.52.0 - 128.30.52.255, and 128.30.52.134 is within that range.
You can verify it for example here: https://www.xarg.org/tools/subnet-calculator/?q=128.30.52.0%2F24

**Comment by EndeavourAccuracy** [comment]
You are right.
For some reason, I read it as 128.30.52.0 or 128.30.52.24.
Closing this issue.
