### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by mgutt** [w3c/markup-validator#56]
Does not work at all:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fipv6.google.com%2F
> HTTP ERROR 404
> Problem accessing //ipv6.google.com/. Reason:
> Not Found

Returns an error:
https://validator.w3.org/nu/?doc=https%3A%2F%2F%5B2001%3A4860%3A0%3A2001%3A%3A68%5D
> IO Error: Connect to [2001:4860:0:2001::68]:443 [/2001:4860:0:2001:0:0:0:68] failed: connect timed out

**Comment by sideshowbarker** [comment]
https://validator.w3.org/nu/ is able to use IPv6 addresses/routing just fine; for example:

* https://validator.w3.org/nu/?doc=http://[2001:15e8:110:92e::cc1e:c0de]
* https://validator.w3.org/nu/?doc=http://[2001:41c8:51:1f3:feff:ff:fe00:b9c]

> [validator.w3.org/nu/?doc=https%3A%2F%2F%5B2001%3A4860%3A0%3A2001%3A%3A68%5D](https://validator.w3.org/nu/?doc=https%3A%2F%2F%5B2001%3A4860%3A0%3A2001%3A%3A68%5D)
>> IO Error: Connect to [2001:4860:0:2001::68]:443 [/2001:4860:0:2001:0:0:0:68] failed: connect timed out

With 2001:4860:0:2001::68 I get that same connection timeout when I test with other tools from the command line — for example, with mtr or traceroute or whatever. It gets routed to 2001:468:601:1::14 but it stops there.

So 2001:4860:0:2001::68 doesn’t demonstrate any problem with IPv6 support in https://validator.w3.org/nu
