### ISSUE TITLE
Custom properties cause an error alert inside RGB and RGBA functions

### ISSUE THREAD

**Issue by adrianoenache** [w3c/markup-validator#61]
Hello there,

The custom properties cause an error alert inside RGB and RGBA functions.

To reproduce use the code in code pen or the HTML in the zip.

https://codepen.io/adrianoenache/pen/JjRdwGm
[bug-custom-properties.zip](https://github.com/w3c/markup-validator/files/6591805/bug-custom-properties.zip)
![bug-custom-properties](https://user-images.githubusercontent.com/3247230/120649755-7ccbe900-c453-11eb-9aa4-29010ad6a6d7.PNG)

Despite the error, it is working in the browsers I tested on mobile and desktop on Edge, Chrome, and Firefox. So I think this is a bug in the validator.

**Comment by dontcallmedom** [comment]
https://github.com/w3c/css-validator/issues/303 is the right place to discuss & track progress on this problem, so closing this one

**Comment by adrianoenache** [comment]
Hi, @dontcallmedom 

Ok, just checking the markup validator use the CSS-validator to validate the CSS inside the <style> tags?

Ok, just checking the markup validator, use the CSS-validator to validate the CSS inside the <style> tags? 

I'm questioning that because the markup validator show fewer errors than the CSS validator, so I supposed the code used to validate it is different.

Please, use the code in the tickets and compare the report in both validators.
https://github.com/w3c/css-validator/issues/303

**Comment by dontcallmedom** [comment]
correct, the markup validator (when used on non-DTD based HTML, in which case it uses https://github.com/validator/validator/ as a back-end) relies on the CSS validator to validate CSS content embedded in HTML (either in `<script>` elements or in `style` attributes.)
