### ISSUE TITLE
check referer and cloudflare deployment

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/markup-validator#68]
validator.w3.org now operating behind CloudFlare webapp firewall possibly requiring hCaptcha breaks the `check/referer` route (from a twitter report)

see also #34 for another limitation of check referer; maybe time to retire that route altogether

**Comment by gosko** [comment]
I updated our Cloudflare firewall config to exempt /check/referer and /check?uri=referer from these challenges.

**Comment by dontcallmedom** [comment]
thanks a lot @gosko!

**Comment by mirabilos** [comment]
Nope, still broken.

### lynx

It gets the correct URL…

```
   30. Using
       https://validator.w3.org/check?uri=http%3A%2F%2Fwww.mirbsd.org%2Fwptg.htm;accept=text%2Fhtml%2C%20te
       xt%2Fplain%2C%20text%2Fsgml%2C%20text%2Fcss%2C%20%2A%2F%2A%3Bq%3D0.01;accept-language=en
```

… but is not allowed to get the result:

![403 for Lynx ☹](https://user-images.githubusercontent.com/861078/162494703-616af24b-f380-49be-b31b-c150463c8391.png)

### Firefox

It still gets the wrong URL:

![wrong URL for Firefox](https://user-images.githubusercontent.com/861078/162494704-37673f6b-88e2-4d7f-a79f-0ee2836a7ba1.png)

That is, / instead of the subpage.

**Comment by gosko** [comment]
Oh, I wasn't aware `/check/referer` had been updated to issue a redirect. I made another small update to our firewall in Cloudflare and it now works well for me using Lynx but not Chrome, likely due to issue #34

**Comment by mirabilos** [comment]
Hi Gerald,

>Oh, I wasn't aware `/check/referer` had been updated to issue a
>redirect. I made another small update to our firewall in Cloudflare and
>it now works well for me using Lynx but not Chrome, likely due to issue

can confirm it works in lynx again, thank you very much❣

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by mirabilos** [comment]
Interestingly enough, it works with lynx but *not* in Firefox. (I am perfectly willing to blame Mozilla for this.)

**Comment by mirabilos** [comment]
… and, of course, (in lynx) the link from there to the jigsaw CSS validator is correct but Cloudflare blocks the request. 🤬
